global:
  scrape_interval: 15s
  evaluation_interval: 15s

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - deployment.environment.name
  keep_identifying_resource_attributes: true

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: citiesservice
    metrics_path: /metrics
    static_configs:
      - targets:
          - citiesservice:80

  - job_name: citiesgrpcservice
    metrics_path: /metrics
    static_configs:
      - targets:
          - citiesgrpcservice:80
